spring:
  security:
    user:
      name: center
      password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
#redis:
#  server: localhost
#  port: 6379
#  password:
#  database: 5
#  pool:
#      maxTotal: 30
#      minIdle: 10
#      maxWaitMillis: 10000