#spring:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: 123456
#    listener:
#      simple:
#        max-concurrency: 8
#        concurrency: 4
#        prefetch: 50
redis:
  server: localhost
  port: 6379
  password:
  database: 5
  pool:
      maxTotal: 30
      minIdle: 10
      maxWaitMillis: 10000
socketio:
  rabbitmq:
    consumer:
      queue: websocket.redirect.queue-A
