#eureka取消注册并且下线的配置，访问/eureka/offline?username=xxx&password=xxx
eureka-client:
  username: msg-server
  password: 123456
spring:
  security:
    user:
      name: center
      password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        max-concurrency: 8
        concurrency: 4
        prefetch: 50


eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

#redis:
#  server: localhost
#  port: 6379
#  password:
#  database: 12

#redis:
#  server: r-wz9l1uaq7hbkntiin4.redis.rds.aliyuncs.com
#  port: 6379
#  password: RfyS8wJZCrM3
#  database: 12
socketio:
  rabbitmq:
    consumer:
      queue: websocket.redirect.queue-A

redis:
  server: localhost
  port: 6379
  password:
  database: 5
  pool:
      maxTotal: 30
      minIdle: 10
      maxWaitMillis: 10000